### ISSUE TITLE
Landing page loads slowly

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-gh-page-assets#13]
I've did some research regarding why our landing page loads slowly and it appears that most of the time spent loading blocking scripts from DX CDN. For some reason they not cached and loads quite slow:
![image](https://cloud.githubusercontent.com/assets/453071/17442710/ae16fb62-5b3f-11e6-81a8-4fc7d6345b38.png)

I suggest to add `async` attribute for all scripts, and run all initialization on `DOMContentLoaded` event

**Comment by inikulin** [comment]
Do the same for https://github.com/DevExpress/testcafe/blob/master/docs/articles/index.html

**Comment by VasilyStrelyaev** [comment]
From what I've just learnt, `async` scripts can still be loading when `DOMContentLoaded` is fired, so the initialization does not happen.

And that's what actually happens.

**Comment by inikulin** [comment]
@VasilyStrelyaev Yeah, you need `defer` attribute then. BTW, https://github.com/DevExpress/testcafe/blob/master/docs/articles/index.html does contain blocking scripts

**Comment by VasilyStrelyaev** [comment]
> does contain blocking scripts

you mean the gallery?
everything else is okay with JS disabled... we should do something with the gallery?

**Comment by inikulin** [comment]
> everything else is okay with JS disabled... we should do something with the gallery?

Yes

**Comment by VasilyStrelyaev** [comment]
This way better?

[http://strelyaev-w8:9090/testcafe/](http://strelyaev-w8:9090/testcafe/)

**Comment by inikulin** [comment]
Yeah
